pool:
  vmImage: 'macOS-10.13'

steps:
  - script: |
      ls /Applications/Xcode*
      gcc --version
      xcode-select -p
      sudo xcode-select -switch /Applications/Xcode_10.app/
      xcode-select -p
      gcc --version
      clang --version

